### ISSUE TITLE
Tidyverse part 2 - purrr and other packages/features

### ISSUE THREAD

**Issue by nielsenmarkus11** [slc-rug/future-meetups#3]
This presentation idea is as a follow up to the introduction to tidyverse and will go more into depth in to purrr for example.

**Comment by danielbride** [comment]
I'm working on a brief presentation on the Tidyverse to present at Intermountain (Analysts Sharing Knowledge mtg.). I would be happy to expand on it in a way that's relevant for this group. I'd particularly love to talk about purrr and could even briefly delve into the newly-emerging tidymodels ecosystem of packages.

**Comment by nielsenmarkus11** [comment]
That would be great! I think the next Meetup we're looking to fill is going to be May. Would that work for you?

Thanks Daniel!

**Comment by danielbride** [comment]
I'm planning to be on parental leave in May, so June might work better if there's nothing planned yet.

**Comment by juliasilge** [comment]
June would work quite well! Does meeting downtown or in Murray work better for you?

**Comment by danielbride** [comment]
I work in Murray, so that would be easiest for me. Should I book a room here to use?

**Comment by juliasilge** [comment]
@nielsenmarkus11 Would you prefer @danielbride to book a room or for you to do it?

**Comment by nielsenmarkus11** [comment]
@danielbride, I'll set up a place to meet.  Intermountain is picky about having groups meetup regularly at the hospital but perhaps we can work with John KW to set up some time at SelectHealth.

**Comment by nielsenmarkus11** [comment]
@danielbride, we've scheduled the SelectHealth auditorium for June 5th at noon.  Does that still work for you?  Also, do you have a short bio/title and description you'd like us to share on the meetup page?

**Comment by danielbride** [comment]
That's perfect. Thanks for setting it up! And here's a bio blurb:

Daniel Bride is a statistical data analyst in cardiovascular research for Intermountain Healthcare. He obtained a BS and MS in Psychology and an MS in Information Systems from the University of Utah. Daniel is enthusiastic about good science and good communication. Outside of work, Daniel tries to make time for running, rock climbing, and reading, but mostly he just does laundry and plays with his kids.

**Comment by juliasilge** [comment]
Hello there, @danielbride! We have the Meetup.com event for your talk next Wednesday set up here:
https://www.meetup.com/slc-rug/events/258684575/
Do you have any questions or concerns as we get ready for the RUG meeting next week? We have a nice group of ~40 folks who have RSVP'd so far. I am looking forward to it! 🎉
