### ISSUE TITLE
Stan

### ISSUE THREAD

**Issue by VectorPosse** [slc-rug/future-meetups#9]
I could present sometime on using the Stan modeling language. There are various topics one could cover depending on background/interest. From the theoretical side, there is the Hamiltonian MCMC stuff that happens under the hood. On the practical side, there are applications that can be coded up in Stan using the RStan interface. It's also a good vehicle for explaining Bayesian hierarchical modeling.

**Comment by nielsenmarkus11** [comment]
Sean, that would be awesome! Could I tentatively put you down for November this year? And as it gets closer I coordinate more with you?

**Comment by VectorPosse** [comment]
Sure, November sounds good.

**Comment by juliasilge** [comment]
Hello @VectorPosse! We are working on planning the November meeting. What day would work for you to present on Stan? We usually meet during the week at lunchtime and could possibly meet downtown or in Murray at IMC, if one works for you? Do you have preferences? Something the week of Nov 5 or 12? Tues/Wed/Thurs?

**Comment by VectorPosse** [comment]
Hi Julia,

Monday through Thursday I have class right up until noon. Would a 12:30
starting time work for people? On Tuesdays and Thursdays, I have class at
2:00, so I'd have to get back (but that should be possible).  Mondays and
Wednesdays are often a little more flexible. There are also a few Fridays I
could make work at 12:00. So what's the priority for the group, a noon
start time, or the day of the week?

**Comment by nielsenmarkus11** [comment]
@VectorPosse, whatever works best for you.  I don't think starting a little later or on a different day than Thursday would have much of an impact.  Thanks for your willingness to present.

**Comment by VectorPosse** [comment]
The best day/time for me would be Friday, November 16 at 12:00 p.m.

If people feel Friday wouldn't get the same draw, my second-best day/time would be Wednesday, November 14 at 12:30 p.m.

**Comment by juliasilge** [comment]
I'm open to trying a Friday. What do you think @nielsenmarkus11?

**Comment by nielsenmarkus11** [comment]
I think we can give Friday a try... I'll try and set something up at Neumont if I can. If not we'll try IHC.  Thanks @VectorPosse!

**Comment by nielsenmarkus11** [comment]
@VectorPosse, I set it up at Neumont Room #209 for Wednesday at 12:30pm.  Is this still okay?

**Comment by VectorPosse** [comment]
Which day?

**Comment by nielsenmarkus11** [comment]
November 14th.

**Comment by VectorPosse** [comment]
Yep, that works great. I'm looking forward to it.

**Comment by nielsenmarkus11** [comment]
Awesome.  We are looking forward to it too. Thank you!

**Comment by nielsenmarkus11** [comment]
Do you have a Title/Summary you would like me to post?  Also, a sentence or two bio?

**Comment by VectorPosse** [comment]
Sure, give me a day or two to put that together.

**Comment by VectorPosse** [comment]
Okay here we go:

Title: Bayesian modeling with Stan

Summary: Recent advances in Markov Chain Monte Carlo (MCMC) simulation have led to the development of a high-level probability modeling language called Stan. In this presentation, I will give a gentle introduction to Bayesian inference using Stan.

Bio: Sean Raleigh received his Ph.D. in mathematics from U.C. San Diego, specializing in geometric topology and knot theory. He is a professor of mathematics at Westminster College and currently chairs the data science program. As part of Sean's professional work, he advocates for Bayesian methods in data analysis and co-directs QUARC, the Quantitative Analysis and Research Cooperative.

**Comment by juliasilge** [comment]
Thanks so much @VectorPosse! I updated the [meetup event](https://www.meetup.com/slc-rug/events/255425482/) with these details.

**Comment by juliasilge** [comment]
Hello there @VectorPosse! Are you all set to present next Wednesday at 12:30pm at Neumont? Looks like we have 30+ folks who have RSVP'd so far.

**Comment by VectorPosse** [comment]
Yep. All set and looking forward to it.

**Comment by nielsenmarkus11** [comment]
The location is confirmed... this time we'll be upstairs at Neumont.

**Comment by nielsenmarkus11** [comment]
@VectorPosse Thank you so much for presenting!  Would you be willing to share your slides on this github page?

**Comment by nielsenmarkus11** [comment]
Nevermind... I see the link to it on there!

**Comment by VectorPosse** [comment]
My pleasure. Thanks for having me.
